### ISSUE TITLE
建議指令可以更改，不需打NBA

### ISSUE THREAD

**Issue by skylovely2005** [kunhou/nba-lineBot#5]
NBA今日賽事 -> 今日賽事
NBA明日賽事 -> 明日賽事
NBA昨日賽事 -> 昨日賽事

需求理由：
用這個chatbot的人應該都知道這是for NBA賽事，可以減少打字的字數

**Comment by skylovely2005** [comment]
如果怕聊天中不小心觸發，可改成簡化一點的指令
如加入#做查詢

#今日賽事

**Comment by kunhou** [comment]
close on
